//! Wayland bindings generated directly from the protocol XML in Gamescope.
//!
//! Keeping the XML as the single source of truth prevents the Rust port from
//! silently assigning different opcodes, enum values, interface names, or
//! versions. Both sides are generated by default. Consumers that only need one
//! side can disable default features and select `client` or `server`.

#![forbid(unsafe_code)]

macro_rules! gamescope_protocol {
    ($path:expr_2021, [$($imports:path),*]) => {
        #[cfg(feature = "client")]
        pub use self::generated::client;

        #[cfg(feature = "server")]
        pub use self::generated::server;

        mod generated {
            #![allow(
                dead_code,
                non_camel_case_types,
                non_upper_case_globals,
                non_snake_case,
                unused_imports,
                unused_unsafe,
                unused_variables
            )]
            #[cfg(feature = "client")]
            pub mod client {
                use wayland_client;
                use wayland_client::protocol::*;
                $(use $imports::{client::*};)*

                pub mod __interfaces {
                    use wayland_client::protocol::__interfaces::*;
                    $(use $imports::{client::__interfaces::*};)*
                    wayland_scanner::generate_interfaces!($path);
                }
                use self::__interfaces::*;

                wayland_scanner::generate_client_code!($path);
            }

            #[cfg(feature = "server")]
            pub mod server {
                use wayland_server;
                use wayland_server::protocol::*;
                $(use $imports::{server::*};)*

                pub mod __interfaces {
                    use wayland_server::protocol::__interfaces::*;
                    $(use $imports::{server::__interfaces::*};)*
                    wayland_scanner::generate_interfaces!($path);
                }
                use self::__interfaces::*;

                wayland_scanner::generate_server_code!($path);
            }
        }
    };
}

/// Gamescope action binding protocol, version 1.
pub mod action_binding {
    gamescope_protocol!("../../protocol/gamescope-action-binding.xml", []);
}

/// Gamescope control protocol, currently version 6.
pub mod control {
    gamescope_protocol!("../../protocol/gamescope-control.xml", []);
}

/// Gamescope input method protocol, currently version 3.
pub mod input_method {
    gamescope_protocol!("../../protocol/gamescope-input-method.xml", []);
}

/// Gamescope `PipeWire` stream discovery protocol, version 1.
pub mod pipewire {
    gamescope_protocol!("../../protocol/gamescope-pipewire.xml", []);
}

/// Unstable Gamescope command and log protocol, version 1.
pub mod private {
    gamescope_protocol!("../../protocol/gamescope-private.xml", []);
}

/// Gamescope `ReShade` control protocol, version 1.
pub mod reshade {
    gamescope_protocol!("../../protocol/gamescope-reshade.xml", []);
}

/// Gamescope Vulkan swapchain metadata protocol, version 1.
pub mod swapchain {
    gamescope_protocol!("../../protocol/gamescope-swapchain.xml", []);
}

/// Legacy Gamescope Xwayland surface override protocol, version 1.
pub mod xwayland {
    gamescope_protocol!("../../protocol/gamescope-xwayland.xml", []);
}

/// Experimental frog color-management protocol consumed by nested Gamescope.
pub mod frog_color_management_v1 {
    gamescope_protocol!("../../protocol/frog-color-management-v1.xml", []);
}

/// The color-management-v1 snapshot consumed by this Gamescope checkout.
pub mod color_management_v1 {
    gamescope_protocol!("../../protocol/color-management-v1.xml", []);
}

/// The layer-shell snapshot served by Gamescope through wlroots.
pub mod wlr_layer_shell_unstable_v1 {
    gamescope_protocol!(
        "../../protocol/wlr-layer-shell-unstable-v1.xml",
        [wayland_protocols::xdg::shell]
    );
}

/// The xdg-toplevel-icon snapshot consumed by the nested Wayland backend.
pub mod xdg_toplevel_icon_v1 {
    gamescope_protocol!(
        "../../protocol/xdg-toplevel-icon-v1.xml",
        [wayland_protocols::xdg::shell]
    );
}

#[cfg(all(test, feature = "server"))]
mod tests {
    use wayland_server::Resource;

    use super::{
        action_binding::server::gamescope_action_binding_manager::GamescopeActionBindingManager,
        color_management_v1::server::wp_color_manager_v1::WpColorManagerV1,
        control::server::gamescope_control::GamescopeControl,
        frog_color_management_v1::server::frog_color_management_factory_v1::FrogColorManagementFactoryV1,
        input_method::server::gamescope_input_method_manager::GamescopeInputMethodManager,
        pipewire::server::gamescope_pipewire::GamescopePipewire,
        private::server::gamescope_private::GamescopePrivate,
        reshade::server::gamescope_reshade::GamescopeReshade,
        swapchain::server::gamescope_swapchain_factory_v2::GamescopeSwapchainFactoryV2,
        wlr_layer_shell_unstable_v1::server::zwlr_layer_shell_v1::ZwlrLayerShellV1,
        xdg_toplevel_icon_v1::server::xdg_toplevel_icon_manager_v1::XdgToplevelIconManagerV1,
        xwayland::server::gamescope_xwayland::GamescopeXwayland,
    };

    #[test]
    fn generated_interfaces_keep_xml_names_and_versions() {
        let interfaces = [
            (
                GamescopeActionBindingManager::interface(),
                "gamescope_action_binding_manager",
                1,
            ),
            (GamescopeControl::interface(), "gamescope_control", 6),
            (
                GamescopeInputMethodManager::interface(),
                "gamescope_input_method_manager",
                3,
            ),
            (GamescopePipewire::interface(), "gamescope_pipewire", 1),
            (GamescopePrivate::interface(), "gamescope_private", 1),
            (GamescopeReshade::interface(), "gamescope_reshade", 1),
            (
                GamescopeSwapchainFactoryV2::interface(),
                "gamescope_swapchain_factory_v2",
                1,
            ),
            (GamescopeXwayland::interface(), "gamescope_xwayland", 1),
            (
                FrogColorManagementFactoryV1::interface(),
                "frog_color_management_factory_v1",
                1,
            ),
            (WpColorManagerV1::interface(), "wp_color_manager_v1", 1),
            (ZwlrLayerShellV1::interface(), "zwlr_layer_shell_v1", 4),
            (
                XdgToplevelIconManagerV1::interface(),
                "xdg_toplevel_icon_manager_v1",
                1,
            ),
        ];

        for (interface, expected_name, expected_version) in interfaces {
            assert_eq!(interface.name, expected_name);
            assert_eq!(interface.version, expected_version);
        }
    }
}
